name: Create Release for HACS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v0.1.0)'
        required: true
      changelog:
        description: 'Changelog description for this release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          body: ${{ github.event.inputs.changelog }}
          token: ${{ secrets.GH_PAT }}
      - name: Upload manifest.json
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: custom_components/xai_conversation/manifest.json
